import { useCallback, useEffect, useMemo, useState } from 'react';
import { Modal, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../hooks/useTheme';
import { fetchDeliveryOrders } from '../../services/api';
import { Spacing, Radius } from '../../constants/theme';
import { formatEAT } from '../../utils/helpers';
import { buildCsvContent, shareCsvAsFile } from '../../utils/exportData';
import { DataCard, EmptyState, SectionTitle } from '../../components/EnterpriseUI';

type Period = 'today' | 'week' | 'month' | 'all';
type ViewMode = 'overview' | 'passed' | 'failed';
const labels: Record<Period, string> = { today: 'Today', week: 'This Week', month: 'This Month', all: 'All Time' };
const materialResults = (job: any) => (job.materialInspection?.materialReceipts || []).map((line: any) => line.initialVisualInspection || 'Pending');
const hasFailedMaterial = (job: any) => materialResults(job).some((result: string) => result === 'Failed');
const overallResult = (job: any) => {
  const results = materialResults(job);
  if (hasFailedMaterial(job)) return 'Failed';
  if (results.length && results.every((result: string) => result === 'Pass')) return 'Pass';
  return 'Pending';
};

export default function InspectorHistoryScreen() {
  const colors = useTheme(); const [orders, setOrders] = useState<any[]>([]); const [refreshing, setRefreshing] = useState(false); const [period, setPeriod] = useState<Period>('month'); const [view, setView] = useState<ViewMode>('overview'); const [exporting, setExporting] = useState(false); const [selected, setSelected] = useState<any>(null);
  const load = useCallback(async () => setOrders((await fetchDeliveryOrders()).filter((job: any) => job.materialInspection?.mrfNumber)), []);
  useEffect(() => { void load(); }, [load]);
  const records = useMemo(() => { const start = new Date(); if (period === 'today') start.setHours(0,0,0,0); else if (period === 'week') start.setDate(start.getDate()-7); else if (period === 'month') start.setMonth(start.getMonth()-1); return orders.filter((job) => period === 'all' || new Date(job.materialInspection.inspectedAt || 0) >= start).sort((a,b) => String(b.materialInspection.inspectedAt).localeCompare(String(a.materialInspection.inspectedAt))); }, [orders, period]);
  const passed = records.filter((job) => overallResult(job) === 'Pass'); const failed = records.filter((job) => overallResult(job) === 'Failed'); const visible = view === 'passed' ? passed : view === 'failed' ? failed : records;
  const refresh = async () => { setRefreshing(true); await load(); setRefreshing(false); };
  const exportCsv = async () => { const headers = ['MIF #','Job ID','PO #','Material','PO Qty','Received Qty','Unit','Result','Inspector']; const rows = records.flatMap((job) => (job.materialInspection.materialReceipts || [{materialName:job.materialName,unit:job.unit}]).map((line:any) => [job.materialInspection.mrfNumber,job.jobId,job.poNumber || '',line.materialName || '',String(line.orderedQuantity ?? ''),String(line.receivedQuantity ?? ''),line.unit || '',line.initialVisualInspection || 'Pending',job.materialInspection.inspectorName || ''])); if (!rows.length) return; setExporting(true); try { await shareCsvAsFile(`Material Inspection History ${labels[period]}`, buildCsvContent(headers,rows)); } finally { setExporting(false); } };
  return <ScrollView style={[styles.page,{backgroundColor:colors.background}]} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { void refresh(); }} tintColor={colors.accent} />}>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{(Object.keys(labels) as Period[]).map((key) => <TouchableOpacity key={key} onPress={() => setPeriod(key)} style={[styles.filter,{borderColor:period===key?'#10B981':colors.border,backgroundColor:period===key?'#10B981':colors.surface}]}><Text style={{color:period===key?'#fff':colors.text,fontWeight:'700'}}>{labels[key]}</Text></TouchableOpacity>)}</ScrollView>
    <View style={styles.metrics}><Metric label="Inspected" value={records.length} color={colors.text} selected={view==='overview'} onPress={() => setView('overview')} colors={colors}/><Metric label="Passed" value={passed.length} color="#047857" selected={view==='passed'} onPress={() => setView('passed')} colors={colors}/><Metric label="Failed" value={failed.length} color="#B91C1C" selected={view==='failed'} onPress={() => setView('failed')} colors={colors}/></View>
    <View style={styles.exports}><TouchableOpacity disabled={exporting} onPress={() => { void exportCsv(); }} style={[styles.csv,{borderColor:colors.border}]}><Text style={{color:colors.text,fontWeight:'800'}}>{exporting ? 'Preparing…' : 'Export CSV'}</Text></TouchableOpacity></View>
    <SectionTitle title={`${view==='overview'?'Inspection History':view==='passed'?'Passed Inspections':'Failed Inspections'} — ${labels[period]} (${visible.length})`} />
    {visible.length ? visible.map((job) => <DataCard key={job.id} onPress={() => setSelected(job)}><View style={styles.row}><View><Text style={styles.mrf}>{job.materialInspection.mrfNumber}</Text><Text style={[styles.job,{color:colors.text}]}>{job.jobId}</Text></View><Text style={{color:overallResult(job)==='Pass'?'#047857':overallResult(job)==='Failed'?'#B91C1C':colors.textMuted,fontWeight:'800'}}>{overallResult(job)}</Text></View><Text style={{color:colors.textMuted}}>{formatEAT(job.materialInspection.inspectedAt)}</Text>{(job.materialInspection.materialReceipts || []).map((line:any) => <Text key={line.materialId} style={{color:colors.text,marginTop:4}}>{line.materialName}: {line.receivedQuantity} {line.unit || ''} · {line.initialVisualInspection || 'Pending'}</Text>)}</DataCard>) : <EmptyState icon="clipboard-outline" title="No inspections found" subtitle="Try another filter or pull down to refresh."/>}
    <Modal visible={Boolean(selected)} transparent animationType="slide" onRequestClose={() => setSelected(null)}><View style={styles.modal}><View style={[styles.detail,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.row}><Text style={[styles.job,{color:colors.text}]}>{selected?.materialInspection?.mrfNumber}</Text><TouchableOpacity onPress={() => setSelected(null)}><Ionicons name="close" size={24} color={colors.text}/></TouchableOpacity></View><Text style={{color:colors.textMuted}}>{selected?.jobId} · {selected?.poNumber || 'No PO'}</Text><Text style={[styles.detailTitle,{color:colors.text}]}>Material receipts</Text>{(selected?.materialInspection?.materialReceipts || []).map((line:any) => <View key={line.materialId} style={styles.row}><Text style={{color:colors.text}}>{line.materialName}</Text><Text style={{color:colors.text,fontWeight:'800'}}>{line.receivedQuantity} {line.unit || ''}</Text></View>)}<Text style={[styles.detailTitle,{color:colors.text}]}>Inspection details</Text><Text style={{color:colors.text}}>Result: {selected?.materialInspection?.initialVisualInspection}</Text>{selected?.materialInspection?.failureReason?<Text style={{color:colors.danger}}>Reason: {selected.materialInspection.failureReason}</Text>:null}</View></View></Modal>
  </ScrollView>;
}
function Metric({label,value,color,selected,onPress,colors}:any) { return <TouchableOpacity onPress={onPress} style={[styles.metric,{backgroundColor:colors.surface,borderColor:selected?color:colors.border}]}><Text style={[styles.metricValue,{color}]}>{value}</Text><Text style={{color:colors.textMuted,fontSize:12}}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({page:{flex:1},content:{padding:Spacing.lg,paddingBottom:Spacing.xs,gap:Spacing.sm},rail:{gap:8,paddingBottom:4},filter:{borderWidth:1,borderRadius:999,paddingHorizontal:13,paddingVertical:8},metrics:{flexDirection:'row',gap:8},metric:{flex:1,borderWidth:1,borderRadius:Radius.md,padding:Spacing.sm,alignItems:'center'},metricValue:{fontSize:21,fontWeight:'900'},exports:{flexDirection:'row',gap:8},csv:{flex:1,borderWidth:1,borderRadius:Radius.md,padding:11,alignItems:'center'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},mrf:{color:'#10B981',fontSize:13,fontWeight:'800'},job:{fontSize:16,fontWeight:'800',marginVertical:3},modal:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.4)'},detail:{borderTopLeftRadius:Radius.lg,borderTopRightRadius:Radius.lg,borderWidth:1,padding:Spacing.lg,gap:Spacing.sm},detailTitle:{fontSize:15,fontWeight:'800',marginTop:Spacing.sm}});
