import { useEffect, useMemo, useState } from 'react';
import {
  Alert,
  RefreshControl,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../hooks/useTheme';
import { Radius, Spacing } from '../../constants/theme';
import { fetchDeliveryOrders } from '../../services/api';
import { formatEAT } from '../../utils/helpers';
import {
  DataCard,
  EmptyState,
  MetricTile,
  PageShell,
  SectionTitle,
  StatusPill,
} from '../../components/EnterpriseUI';

/* ─────────── CSV / PDF helpers (inline, mirroring utils/exportData.ts) ─────────── */

function escapeCsvField(value: any): string {
  if (value == null || value === undefined) return '';
  const str = String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function formatCsv(headers: string[], rows: string[][]): string {
  const hdr = headers.map(escapeCsvField).join(',');
  const body = rows.map((row) => row.map(escapeCsvField).join(',')).join('\n');
  return `${hdr}\n${body}`;
}

function buildHtmlTable(headers: string[], rows: string[][], title: string): string {
  const headerCells = headers
    .map(
      (h) =>
        `<th style="padding:10px 14px; background:#1B2A4A; color:#fff; font-weight:700; text-align:left; border:1px solid #ddd;">${h}</th>`,
    )
    .join('');
  const bodyRows = rows
    .map((row, i) => {
      const bg = i % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
      const cells = row
        .map(
          (cell) =>
            `<td style="padding:8px 14px; border:1px solid #ddd;">${cell || '—'}</td>`,
        )
        .join('');
      return `<tr style="background:${bg};">${cells}</tr>`;
    })
    .join('');

  return `
    <html>
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
    <body style="font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1E293B;">
      <h1 style="color: #1B2A4A; margin-bottom: 4px;">Trucks Sphere</h1>
      <h2 style="color: #475569; font-size: 18px; margin-top: 0; margin-bottom: 24px;">${title}</h2>
      <p style="color: #94A3B8; font-size: 12px;">Exported on ${new Date().toLocaleString('en-KE', {
        timeZone: 'Africa/Nairobi',
      })}</p>
      <table style="width:100%; border-collapse:collapse; font-size:13px; margin-top:12px;">
        <thead><tr>${headerCells}</tr></thead>
        <tbody>${bodyRows}</tbody>
      </table>
      <p style="color: #94A3B8; font-size: 10px; margin-top: 32px; text-align:center;">Generated by Trucks Sphere</p>
    </body>
    </html>
  `;
}

async function shareCsv(title: string, headers: string[], rows: string[][]) {
  try {
    const csv = formatCsv(headers, rows);
    await Share.share({ message: csv, title });
  } catch (e: any) {
    if (e?.message !== 'User did not share') {
      Alert.alert('Export Error', e?.message || 'Failed to share CSV');
    }
  }
}

async function sharePdf(title: string, headers: string[], rows: string[][]) {
  try {
    const html = buildHtmlTable(headers, rows, title);
    await Share.share({ message: html, title });
  } catch (e: any) {
    if (e?.message !== 'User did not share') {
      Alert.alert('Export Error', e?.message || 'Failed to share');
    }
  }
}

/* ─────────── Filter Options ─────────── */

type FilterPeriod = 'today' | 'week' | 'month';

const FILTER_LABELS: Record<FilterPeriod, string> = {
  today: 'Today',
  week: 'This Week',
  month: 'This Month',
};

/* ─────────── Component ─────────── */

export default function OperatorQuarryHistoryScreen() {
  const colors = useTheme();
  const [deliveries, setDeliveries] = useState<any[]>([]);
  const [refreshing, setRefreshing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<FilterPeriod>('today');

  const loadData = async () => {
    setRefreshing(true);
    try {
      const data = (await fetchDeliveryOrders()) || [];
      setDeliveries(data);
    } catch {
    } finally {
      setRefreshing(false);
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  /* ─── Filtering Logic ─── */

  const now = new Date();

  const getStartOfPeriod = (period: FilterPeriod): Date => {
    const d = new Date(now);
    if (period === 'today') {
      d.setHours(0, 0, 0, 0);
    } else if (period === 'week') {
      const day = d.getDay();
      const diff = d.getDate() - day + (day === 0 ? -6 : 1); // Monday
      d.setDate(diff);
      d.setHours(0, 0, 0, 0);
    } else {
      d.setDate(1);
      d.setHours(0, 0, 0, 0);
    }
    return d;
  };

  const startDate = getStartOfPeriod(filter);

  const activeQueue = deliveries.filter(
    (d) => !['delivered', 'completed', 'cancelled'].includes(d.status),
  );

  const completedRecords = useMemo(() => {
    return deliveries
      .filter(
        (d) =>
          d.status === 'delivered' || d.status === 'completed',
      )
      .filter((d) => {
        const updated = new Date(d.updatedAt || d.createdAt);
        return updated >= startDate;
      })
      .sort(
        (a, b) =>
          new Date(b.updatedAt || b.createdAt).getTime() -
          new Date(a.updatedAt || a.createdAt).getTime(),
      );
  }, [deliveries, startDate]);

  /* ─── Export Logic ─── */

  const exportHeaders = [
    'Job ID',
    'PO Number',
    'Driver',
    'Truck Plate',
    'Material',
    'Qty Ordered (t)',
    'Weigh In (t)',
    'Weigh Out (t)',
    'Net (t)',
    'Status',
    'Updated',
  ];

  const buildExportRows = (records: any[]): string[][] =>
    records.map((r) => [
      r.jobId || '',
      r.poNumber || '',
      r.driverName || '',
      r.plateNumber || '',
      r.materialName || '',
      String(r.quantityOrdered ?? ''),
      r.weighInWeight != null ? r.weighInWeight.toFixed(1) : '—',
      r.weighOutWeight != null ? r.weighOutWeight.toFixed(1) : '—',
      r.netWeight != null ? r.netWeight.toFixed(1) : '—',
      r.status || '',
      r.updatedAt || r.createdAt || '',
    ]);

  const handleDownloadCSV = async () => {
    const rows = buildExportRows(completedRecords);
    await shareCsv(`Quarry_History_${FILTER_LABELS[filter]}`, exportHeaders, rows);
  };

  const handleDownloadPDF = async () => {
    const rows = buildExportRows(completedRecords);
    await sharePdf(`Quarry History — ${FILTER_LABELS[filter]}`, exportHeaders, rows);
  };

  /* ─── Summary Stats ─── */

  const totalNetToday = completedRecords.reduce(
    (sum, r) => sum + (r.netWeight || 0),
    0,
  );

  return (
    <PageShell
      refreshControl={
        <RefreshControl
          refreshing={refreshing}
          onRefresh={loadData}
          tintColor={colors.primary}
        />
      }
    >
      {/* Summary Tiles */}
      <View style={styles.metricRow}>
        <MetricTile
          icon="clipboard"
          label="Active Queue"
          value={activeQueue.length}
          tone={colors.warning}
        />
        <MetricTile
          icon="checkmark-done"
          label="Completed"
          value={completedRecords.length}
          tone={colors.success}
        />
        <MetricTile
          icon="cube"
          label={`Net (${FILTER_LABELS[filter]})`}
          value={`${totalNetToday.toFixed(1)}T`}
          tone={colors.primary}
        />
      </View>

      {/* Filter Pills */}
      <View style={styles.filterRow}>
        {(['today', 'week', 'month'] as FilterPeriod[]).map((period) => {
          const active = filter === period;
          return (
            <TouchableOpacity
              key={period}
              style={[
                styles.filterPill,
                {
                  backgroundColor: active
                    ? colors.primary
                    : colors.inputBg,
                  borderColor: active ? colors.primary : colors.border,
                },
              ]}
              onPress={() => setFilter(period)}
            >
              <Ionicons
                name={
                  period === 'today'
                    ? 'today-outline'
                    : period === 'week'
                    ? 'calendar-outline'
                    : 'calendar-number-outline'
                }
                size={14}
                color={active ? '#FFFFFF' : colors.textSecondary}
              />
              <Text
                style={[
                  styles.filterPillText,
                  { color: active ? '#FFFFFF' : colors.textSecondary },
                ]}
              >
                {FILTER_LABELS[period]}
              </Text>
            </TouchableOpacity>
          );
        })}
      </View>

      {/* Export Actions */}
      <View style={styles.exportRow}>
        <TouchableOpacity
          style={[styles.exportBtn, { backgroundColor: '#2563EB' }]}
          onPress={handleDownloadCSV}
        >
          <Ionicons name="document-text-outline" size={16} color="#FFFFFF" />
          <Text style={styles.exportBtnText}>Download CSV</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.exportBtn, { backgroundColor: '#7C3AED' }]}
          onPress={handleDownloadPDF}
        >
          <Ionicons name="document-outline" size={16} color="#FFFFFF" />
          <Text style={styles.exportBtnText}>Download PDF</Text>
        </TouchableOpacity>
      </View>

      {/* Active Queue Logs */}
      <SectionTitle title={`Active Queue (${activeQueue.length})`} />
      {loading ? (
        <DataCard>
          <Text style={{ fontSize: 14, color: colors.textMuted }}>Loading...</Text>
        </DataCard>
      ) : activeQueue.length ? (
        activeQueue.slice(0, 15).map((item) => (
          <DataCard key={item.id}>
            <View style={styles.tableHeaderRow}>
              <Text style={[styles.tableJobId, { color: colors.text }]}>
                {item.jobId}
              </Text>
              <StatusPill status={item.status} compact />
            </View>
            <View style={styles.tableRow}>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Driver</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.driverName || '—'}
                </Text>
              </View>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Truck</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.plateNumber || '—'}
                </Text>
              </View>
            </View>
            <View style={styles.tableRow}>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Material</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.materialName || '—'}
                </Text>
              </View>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Qty</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.quantityOrdered ?? '—'} t
                </Text>
              </View>
            </View>
            <Text style={[styles.tableTimestamp, { color: colors.textTertiary }]}>
              Updated: {formatEAT(item.updatedAt || item.createdAt)}
            </Text>
          </DataCard>
        ))
      ) : (
        <EmptyState
          icon="clipboard-outline"
          title="No active jobs"
          subtitle="Queue is currently empty."
        />
      )}

      {/* Completed Submissions */}
      <SectionTitle
        title={`Completed — ${FILTER_LABELS[filter]} (${completedRecords.length})`}
      />
      {loading ? (
        <DataCard>
          <Text style={{ fontSize: 14, color: colors.textMuted }}>Loading...</Text>
        </DataCard>
      ) : completedRecords.length ? (
        completedRecords.map((item) => (
          <DataCard key={item.id}>
            <View style={styles.tableHeaderRow}>
              <View style={{ flex: 1 }}>
                <Text style={[styles.tableJobId, { color: colors.text }]}>
                  {item.jobId}
                </Text>
                <Text style={[styles.tablePo, { color: colors.textMuted }]}>
                  {item.poNumber || '—'}
                </Text>
              </View>
              <StatusPill status={item.status} compact />
            </View>
            <View style={styles.tableRow}>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Driver</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.driverName || '—'}
                </Text>
              </View>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Truck</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.plateNumber || '—'}
                </Text>
              </View>
            </View>
            <View style={styles.tableRow}>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Material</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.materialName || '—'}
                </Text>
              </View>
              <View style={styles.tableCell}>
                <Text style={[styles.tableLabel, { color: colors.textMuted }]}>Qty</Text>
                <Text style={[styles.tableValue, { color: colors.text }]}>
                  {item.quantityOrdered ?? '—'} t
                </Text>
              </View>
            </View>

            {/* Weight Summary Row for Completed */}
            <View style={[styles.weightSummary, { backgroundColor: colors.inputBg, borderColor: colors.border }]}>
              <View style={styles.weightCell}>
                <Text style={[styles.wLabel, { color: colors.textMuted }]}>IN</Text>
                <Text style={[styles.wValue, { color: '#2563EB' }]}>
                  {item.weighInWeight != null ? `${item.weighInWeight.toFixed(1)}T` : '—'}
                </Text>
              </View>
              <View style={styles.weightCell}>
                <Text style={[styles.wLabel, { color: colors.textMuted }]}>OUT</Text>
                <Text style={[styles.wValue, { color: '#7C3AED' }]}>
                  {item.weighOutWeight != null ? `${item.weighOutWeight.toFixed(1)}T` : '—'}
                </Text>
              </View>
              <View style={styles.weightCell}>
                <Text style={[styles.wLabel, { color: colors.textMuted }]}>NET</Text>
                <Text style={[styles.wValue, { color: colors.success, fontSize: 18 }]}>
                  {item.netWeight != null ? `${item.netWeight.toFixed(1)}T` : '—'}
                </Text>
              </View>
            </View>

            <Text style={[styles.tableTimestamp, { color: colors.textTertiary }]}>
              Completed: {formatEAT(item.updatedAt || item.createdAt)}
            </Text>
          </DataCard>
        ))
      ) : (
        <EmptyState
          icon="checkmark-done-outline"
          title="No completed records"
          subtitle={`No submissions found for ${FILTER_LABELS[filter].toLowerCase()}.`}
        />
      )}

      {/* Bottom spacing */}
      <View style={{ height: Spacing['4xl'] }} />
    </PageShell>
  );
}

/* ─── Styles ─── */

const styles = StyleSheet.create({
  metricRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  // Filters
  filterRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.full,
    borderWidth: 1,
  },
  filterPillText: { fontSize: 13, fontWeight: '700' },
  // Export
  exportRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  exportBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
    minHeight: 44,
  },
  exportBtnText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800' },
  // Table rows
  tableHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Spacing.sm,
  },
  tableJobId: { fontSize: 15, fontWeight: '700' },
  tablePo: { fontSize: 11, fontWeight: '600', marginTop: 2 },
  tableRow: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginBottom: 4,
  },
  tableCell: { flex: 1 },
  tableLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', marginBottom: 2 },
  tableValue: { fontSize: 13, fontWeight: '600' },
  tableTimestamp: { fontSize: 12, marginTop: Spacing.sm },
  // Weight summary for completed
  weightSummary: {
    flexDirection: 'row',
    borderRadius: Radius.md,
    borderWidth: 1,
    padding: Spacing.sm,
    marginTop: Spacing.sm,
    gap: Spacing.xs,
  },
  weightCell: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 4,
  },
  wLabel: { fontSize: 10, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5 },
  wValue: { fontSize: 14, fontWeight: '800', marginTop: 2 },
});