import { useEffect, useState } from 'react';
import {
  ActivityIndicator,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../hooks/useTheme';
import { Radius, Spacing } from '../../constants/theme';
import { fetchDeliveryOrders } from '../../services/api';
import { formatEAT, generateReceiptNoteId } from '../../utils/helpers';

export default function ReceiptNoteScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const colors = useTheme();
  const [loading, setLoading] = useState(true);
  const [delivery, setDelivery] = useState<any>(null);

  useEffect(() => {
    (async () => {
      try {
        const orders = await fetchDeliveryOrders({ jobId: id });
        if (orders && orders.length > 0) {
          const d = orders[0];
          setDelivery({
            ...d,
            receiptNoteId: d.receiptNoteId || generateReceiptNoteId(d.jobId),
          });
        }
      } catch {} finally {
        setLoading(false);
      }
    })();
  }, [id]);

  if (loading) {
    return (
      <View style={[styles.centered, { backgroundColor: colors.background }]}>
        <ActivityIndicator size="large" color={colors.primary} />
        <Text style={{ color: colors.textMuted, marginTop: 12 }}>Loading receipt note...</Text>
      </View>
    );
  }

  if (!delivery) {
    return (
      <View style={[styles.centered, { backgroundColor: colors.background }]}>
        <Ionicons name="document-outline" size={48} color={colors.textTertiary} />
        <Text style={{ color: colors.textMuted, marginTop: 12, fontSize: 16 }}>Receipt note not found</Text>
        <TouchableOpacity
          style={[styles.backBtn, { backgroundColor: colors.primary }]}
          onPress={() => router.back()}
        >
          <Text style={{ color: '#FFFFFF', fontWeight: '700' }}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const rn = delivery.receiptNoteId;
  const jobId = delivery.jobId;
  const poNumber = delivery.poNumber || 'N/A';
  const driverName = delivery.driverName || 'N/A';
  const plateNumber = delivery.plateNumber || 'N/A';
  const vendorName = delivery.vendorName || 'N/A';
  const vendorId = delivery.vendorId || '';
  const materialName = delivery.materialName || 'N/A';
  const quantityOrdered = delivery.quantityOrdered || 0;
  const quarryName = delivery.quarryName || 'N/A';
  const siteName = delivery.siteName || 'N/A';
  const siteWeighIn = delivery.siteWeighInWeight ?? null;
  const siteWeighOut = delivery.siteWeighOutWeight ?? null;
  const siteNet = delivery.siteNetWeight ?? delivery.quantityDelivered ?? null;
  const quarryNet = delivery.netWeight ?? null;

  const handleShare = async () => {
    const msg = `Receipt Note: ${rn}
Job ID: ${jobId}
PO: ${poNumber}
Driver: ${driverName} | Truck: ${plateNumber}
Vendor: ${vendorName}
Material: ${materialName} | Ordered: ${quantityOrdered} t
Route: ${quarryName} → ${siteName}
Site Arrival: ${siteWeighIn != null ? siteWeighIn.toFixed(1) + ' T' : 'N/A'}
Site Weigh Out: ${siteWeighOut != null ? siteWeighOut.toFixed(1) + ' T' : 'N/A'}
Site Net: ${siteNet != null ? siteNet.toFixed(1) + ' T' : 'N/A'}
Quarry Net: ${quarryNet != null ? quarryNet.toFixed(1) + ' T' : 'N/A'}
Finalized: ${formatEAT(delivery.receivedAt || delivery.updatedAt)}
Generated by Trucks Sphere`;
    await Share.share({ message: msg, title: `RN_${rn}` });
  };

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: colors.background }]}
      contentContainerStyle={styles.content}
    >
      {/* Receipt Note Card */}
      <View
        style={[
          styles.card,
          { backgroundColor: colors.surface, borderColor: colors.border },
        ]}
      >
        {/* Header */}
        <View style={styles.cardHeader}>
          <View style={[styles.rnIconWrap, { backgroundColor: '#10B98115' }]}>
            <Ionicons name="receipt" size={32} color="#10B981" />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={[styles.rnTitle, { color: '#10B981' }]}>{rn}</Text>
            <Text style={[styles.rnLabel, { color: colors.textMuted }]}>
              Receipt Note
            </Text>
          </View>
        </View>

        {/* Job Info */}
        <SectionBlock title="DOCUMENT DETAILS" colors={colors}>
          <RNRow label="Job ID" value={jobId} colors={colors} />
          <RNRow label="Purchase Order" value={poNumber} colors={colors} />
          <RNRow
            label="Finalized"
            value={formatEAT(delivery.receivedAt || delivery.updatedAt)}
            colors={colors}
          />
        </SectionBlock>

        {/* Parties */}
        <SectionBlock title="PARTIES" colors={colors}>
          <RNRow label="Driver" value={driverName} colors={colors} />
          <RNRow label="Truck" value={plateNumber} colors={colors} />
          <RNRow
            label="Vendor"
            value={vendorName}
            colors={colors}
            tappable={!!vendorId}
            onPress={() => vendorId && router.push(`/screens/vendor-detail?id=${vendorId}` as any)}
          />
        </SectionBlock>

        {/* Route */}
        <SectionBlock title="ROUTE" colors={colors}>
          <RNRow label="Origin" value={quarryName} colors={colors} />
          <RNRow label="Destination" value={siteName} colors={colors} />
          <RNRow label="Material" value={materialName} colors={colors} />
          <RNRow label="Ordered" value={`${quantityOrdered} tonnes`} colors={colors} />
        </SectionBlock>

        {/* Weight Record */}
        <SectionBlock title="WEIGHT RECORD" colors={colors}>
          <RNRow
            label="Site Arrival (Gross)"
            value={siteWeighIn != null ? `${siteWeighIn.toFixed(1)} T` : 'N/A'}
            colors={colors}
            valueColor="#F59E0B"
          />
          <RNRow
            label="Site Weigh Out (Tare)"
            value={siteWeighOut != null ? `${siteWeighOut.toFixed(1)} T` : 'N/A'}
            colors={colors}
            valueColor="#8B5CF6"
          />
          <View style={styles.netDivider} />
          <RNRow
            label="Site Net Weight"
            value={siteNet != null ? `${siteNet.toFixed(1)} T` : 'N/A'}
            colors={colors}
            valueColor="#10B981"
            bold
          />
          {quarryNet != null && (
            <RNRow
              label="Quarry Net (Reference)"
              value={`${quarryNet.toFixed(1)} T`}
              colors={colors}
              valueColor="#2563EB"
            />
          )}
        </SectionBlock>

        {/* Difference */}
        {siteNet != null && quantityOrdered > 0 && (
          <View
            style={[
              styles.diffBanner,
              {
                backgroundColor:
                  Math.abs(quantityOrdered - siteNet) > 0.5
                    ? '#FEF2F2'
                    : '#F0FDF4',
                borderColor:
                  Math.abs(quantityOrdered - siteNet) > 0.5
                    ? '#FECACA'
                    : '#BBF7D0',
              },
            ]}
          >
            <Ionicons
              name={
                Math.abs(quantityOrdered - siteNet) > 0.5
                  ? 'warning-outline'
                  : 'checkmark-circle-outline'
              }
              size={18}
              color={
                Math.abs(quantityOrdered - siteNet) > 0.5
                  ? '#DC2626'
                  : '#16A34A'
              }
            />
            <Text
              style={{
                flex: 1,
                fontSize: 12,
                fontWeight: '700',
                color:
                  Math.abs(quantityOrdered - siteNet) > 0.5
                    ? '#991B1B'
                    : '#15803D',
              }}
            >
              vs Ordered ({quantityOrdered}T): Δ{' '}
              {(quantityOrdered - siteNet) > 0 ? '+' : ''}
              {(quantityOrdered - siteNet).toFixed(2)}T
            </Text>
          </View>
        )}
      </View>

      {/* Actions */}
      <View style={styles.actionRow}>
        <TouchableOpacity
          style={[styles.actionBtn, { backgroundColor: '#10B981' }]}
          onPress={handleShare}
        >
          <Ionicons name="share-outline" size={18} color="#FFFFFF" />
          <Text style={styles.actionBtnText}>Share</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[
            styles.actionBtn,
            { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1 },
          ]}
          onPress={() => router.back()}
        >
          <Text style={[styles.actionBtnTextAlt, { color: colors.textSecondary }]}>
            Back
          </Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const SectionBlock = ({ title, colors, children }: { title: string; colors: any; children: React.ReactNode }) => (
  <View style={[styles.section, { borderColor: colors.border }]}>
    <Text style={[styles.sectionTitle, { color: colors.textMuted }]}>{title}</Text>
    {children}
  </View>
);

const RNRow = ({
  label,
  value,
  colors,
  valueColor,
  bold,
  tappable,
  onPress,
}: {
  label: string;
  value: string;
  colors: any;
  valueColor?: string;
  bold?: boolean;
  tappable?: boolean;
  onPress?: () => void;
}) => (
  <View style={styles.rnRow}>
    <Text style={[styles.rnLabel, { color: colors.textMuted }]}>{label}</Text>
    {tappable ? (
      <TouchableOpacity onPress={onPress}>
        <Text
          style={[
            styles.rnValue,
            { color: valueColor || colors.primary, fontWeight: bold ? '800' : '600', textDecorationLine: 'underline' },
          ]}
        >
          {value}
        </Text>
      </TouchableOpacity>
    ) : (
      <Text
        style={[
          styles.rnValue,
          { color: valueColor || colors.text, fontWeight: bold ? '800' : '600' },
        ]}
      >
        {value}
      </Text>
    )}
  </View>
);

const styles = StyleSheet.create({
  container: { flex: 1 },
  content: { padding: Spacing.lg, paddingBottom: Spacing['4xl'] },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.xl },
  backBtn: { marginTop: 16, paddingHorizontal: 20, paddingVertical: 10, borderRadius: Radius.md },
  card: { borderRadius: Radius.xl, borderWidth: 1, padding: Spacing.lg },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  rnIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rnTitle: { fontSize: 16, fontWeight: '900', textTransform: 'uppercase' },
  rnLabel: { fontSize: 11, fontWeight: '700', marginTop: 2 },
  section: {
    borderTopWidth: 1,
    paddingTop: Spacing.md,
    marginBottom: Spacing.md,
    gap: 4,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  rnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 3,
  },
  rnLabel: { fontSize: 12, fontWeight: '600' },
  rnValue: { fontSize: 13 },
  netDivider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 4 },
  diffBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: Radius.md,
    borderWidth: 1,
    padding: Spacing.md,
    marginTop: Spacing.sm,
  },
  actionRow: { flexDirection: 'row', gap: Spacing.md, marginTop: Spacing.lg },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
    gap: Spacing.sm,
  },
  actionBtnText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  actionBtnTextAlt: { fontSize: 14, fontWeight: '600' },
});