import { Platform, Alert, Share } from 'react-native';
import { fetchDrivers, fetchVehicles, fetchPurchaseOrders, fetchDeliveryOrders, fetchVendors } from '../services/api';

function escapeCsvField(value: any): string {
  if (value == null || value === undefined) return '';
  const str = String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function formatCsv(headers: string[], rows: string[][]): string {
  const hdr = headers.map(escapeCsvField).join(',');
  const body = rows.map(row => row.map(escapeCsvField).join(',')).join('\n');
  return `${hdr}\n${body}`;
}

function buildHtmlTable(headers: string[], rows: string[][], title: string): string {
  const headerCells = headers.map(h => `<th style="padding:10px 14px; background:#1B2A4A; color:#fff; font-weight:700; text-align:left; border:1px solid #ddd;">${h}</th>`).join('');
  const bodyRows = rows.map((row, i) => {
    const bg = i % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
    const cells = row.map(cell => `<td style="padding:8px 14px; border:1px solid #ddd;">${cell || '—'}</td>`).join('');
    return `<tr style="background:${bg};">${cells}</tr>`;
  }).join('');

  return `
    <html>
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
    <body style="font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1E293B;">
      <h1 style="color: #1B2A4A; margin-bottom: 4px;">Trucks Sphere</h1>
      <h2 style="color: #475569; font-size: 18px; margin-top: 0; margin-bottom: 24px;">${title}</h2>
      <p style="color: #94A3B8; font-size: 12px;">Exported on ${new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })}</p>
      <table style="width:100%; border-collapse:collapse; font-size:13px; margin-top:12px;">
        <thead><tr>${headerCells}</tr></thead>
        <tbody>${bodyRows}</tbody>
      </table>
      <p style="color: #94A3B8; font-size: 10px; margin-top: 32px; text-align:center;">Generated by Trucks Sphere</p>
    </body>
    </html>
  `;
}

async function shareCsv(title: string, headers: string[], rows: string[][]) {
  try {
    const csv = formatCsv(headers, rows);
    await Share.share({
      message: csv,
      title: title,
    });
  } catch (e: any) {
    if (e?.message !== 'User did not share') {
      Alert.alert('Export Error', e?.message || 'Failed to share CSV');
    }
  }
}

async function sharePdf(title: string, headers: string[], rows: string[][]) {
  try {
    const html = buildHtmlTable(headers, rows, title);
    await Share.share({
      message: html,
      title: title,
    });
  } catch (e: any) {
    if (e?.message !== 'User did not share') {
      Alert.alert('Export Error', e?.message || 'Failed to share');
    }
  }
}

// ============== DELIVERY NOTE EXPORT ==============

export interface DeliveryNoteExportData {
  jobId: string;
  poNumber: string;
  vendorName: string;
  driverName: string;
  plateNumber: string;
  materialName: string;
  quantityOrdered: number;
  quarryName: string;
  siteName: string;
  netWeight: string;
  status: string;
  createdAt: string;
  weighInWeight?: string;
  weighOutWeight?: string;
}

export async function shareDeliveryNoteCSV(data: DeliveryNoteExportData) {
  const headers = ['Field', 'Value'];
  const rows = [
    ['Delivery Note #', data.jobId],
    ['Purchase Order', data.poNumber],
    ['Vendor', data.vendorName],
    ['Driver', data.driverName],
    ['Truck', data.plateNumber],
    ['Material', data.materialName],
    ['Ordered Qty', `${data.quantityOrdered} tonnes`],
    ['Origin', data.quarryName],
    ['Destination', data.siteName],
    ['Weigh-In', data.weighInWeight ? `${data.weighInWeight} t` : '—'],
    ['Weigh-Out', data.weighOutWeight ? `${data.weighOutWeight} t` : '—'],
    ['Net Weight', `${data.netWeight} tonnes`],
    ['Status', data.status.replace(/_/g, ' ').toUpperCase()],
    ['Date Created', data.createdAt],
  ];
  await shareCsv(`Delivery_Note_${data.jobId}`, headers, rows);
}

export async function shareDeliveryNotePDF(data: DeliveryNoteExportData) {
  const headers = ['Field', 'Value'];
  const rows = [
    ['Delivery Note #', data.jobId],
    ['Purchase Order', data.poNumber],
    ['Vendor', data.vendorName],
    ['Driver', data.driverName],
    ['Truck', data.plateNumber],
    ['Material', data.materialName],
    ['Ordered Qty', `${data.quantityOrdered} tonnes`],
    ['Origin', data.quarryName],
    ['Destination', data.siteName],
    ['Weigh-In', data.weighInWeight ? `${data.weighInWeight} t` : '—'],
    ['Weigh-Out', data.weighOutWeight ? `${data.weighOutWeight} t` : '—'],
    ['Net Weight', `${data.netWeight} tonnes`],
    ['Status', data.status.replace(/_/g, ' ').toUpperCase()],
    ['Date Created', data.createdAt],
  ];
  await sharePdf(`Delivery Note - ${data.jobId}`, headers, rows);
}

// ============== SYSTEM-WIDE EXPORTS ==============

export type ExportEntity = 'drivers' | 'trucks' | 'purchase_orders' | 'deliveries' | 'vendors' | 'all';

export async function exportDataAsCSV(entity: ExportEntity) {
  await doExport(entity, 'csv');
}

export async function exportDataAsPDF(entity: ExportEntity) {
  await doExport(entity, 'pdf');
}

async function doExport(entity: ExportEntity, format: 'csv' | 'pdf') {
  try {
    let title = '';
    let headers: string[] = [];
    let rows: string[][] = [];

    if (entity === 'drivers' || entity === 'all') {
      const drivers = await fetchDrivers();
      title += title ? ' + Drivers' : 'Drivers';
      if (entity === 'drivers') {
        headers = ['Name', 'Phone', 'Email', 'License', 'License Expiry', 'Status', 'Vendor ID', 'Assigned Truck', 'Created'];
        rows = drivers.map((d: any) => [
          d.name, d.phone, d.email || '', d.licenseNumber, d.licenseExpiry || '',
          d.status, d.vendorId || '', d.assignedTruckId || '', d.createdAt || '',
        ]);
      } else {
        const dHeaders = ['Type', 'Name', 'Phone', 'Email', 'License', 'Status', 'Created'];
        const dRows = drivers.map((d: any) => [
          'Driver', d.name, d.phone, d.email || '', d.licenseNumber, d.status, d.createdAt || '',
        ]);
        headers = dHeaders;
        rows = dRows;
      }
    }

    if (entity === 'trucks' || entity === 'all') {
      const vehicles = await fetchVehicles();
      const prefix = title ? ' + ' : '';
      title += `${prefix}Trucks`;
      if (entity === 'trucks') {
        headers = ['Plate', 'Model', 'Make', 'Year', 'Color', 'Capacity (t)', 'Status', 'Vendor', 'Driver', 'Insurance', 'Last Inspection'];
        rows = vehicles.map((v: any) => [
          v.plateNumber, v.model, v.make, String(v.year), v.color, String(v.capacity),
          v.status, v.vendorName || '', v.driverName || '', v.insuranceExpiry || '', v.lastInspection || '',
        ]);
      } else {
        const vHeaders = headers.length === 0 ? ['Type', 'Plate', 'Model', 'Make', 'Status', 'Capacity (t)'] : headers;
        const vRows = vehicles.map((v: any) => [
          'Truck', v.plateNumber, v.model, v.make, v.status, String(v.capacity),
        ]);
        if (headers.length === 0) {
          headers = vHeaders;
          rows = vRows;
        } else {
          rows = rows.map((row, i) => [...row, ...(vRows[i] || [])]);
          headers = [...headers, ...vHeaders.slice(1)];
        }
      }
    }

    if (entity === 'purchase_orders' || entity === 'all') {
      const orders = await fetchPurchaseOrders();
      if (entity === 'purchase_orders') {
        title = 'Purchase Orders';
        headers = ['PO Number', 'Vendor', 'Material', 'Quantity', 'Unit', 'Unit Price', 'Total', 'Status', 'Quarry', 'Site', 'Created'];
        rows = orders.map((o: any) => [
          o.poNumber, o.vendorName, o.materialName, String(o.quantity), o.unit,
          String(o.unitPrice), String(o.totalAmount), o.status, o.quarryName, o.siteName, o.createdAt,
        ]);
      } else {
        title += ` + Purchase Orders`;
        const poHeaders = ['Type', 'PO Number', 'Vendor', 'Material', 'Qty', 'Status', 'Total (KES)'];
        const poRows = orders.map((o: any) => [
          'Order', o.poNumber, o.vendorName, o.materialName, `${o.quantity} ${o.unit}`, o.status, `KES ${o.totalAmount?.toLocaleString()}`,
        ]);
        rows = rows.map((row, i) => [...row, ...(poRows[i] || [])]);
        headers = [...headers, ...poHeaders.slice(1)];
      }
    }

    if (entity === 'deliveries' || entity === 'all') {
      const deliveries = await fetchDeliveryOrders();
      if (entity === 'deliveries') {
        title = 'Deliveries';
        headers = ['Job ID', 'PO Number', 'Vendor', 'Driver', 'Truck', 'Material', 'Ordered Qty', 'Net Weight', 'Status', 'Quarry', 'Site', 'Created'];
        rows = deliveries.map((d: any) => [
          d.jobId, d.poNumber, d.vendorName, d.driverName, d.plateNumber, d.materialName,
          `${d.quantityOrdered} ${d.unit || 'tonnes'}`, d.netWeight ? `${d.netWeight} t` : '—',
          d.status, d.quarryName, d.siteName, d.createdAt,
        ]);
      } else {
        title += ` + Deliveries`;
        const dHeaders = ['Type', 'Job ID', 'Driver', 'Truck', 'Material', 'Status'];
        const dRows = deliveries.map((d: any) => [
          'Delivery', d.jobId, d.driverName, d.plateNumber, d.materialName, d.status,
        ]);
        rows = rows.map((row, i) => [...row, ...(dRows[i] || [])]);
        headers = [...headers, ...dHeaders.slice(1)];
      }
    }

    if (entity === 'vendors' || entity === 'all') {
      const vendors = await fetchVendors();
      if (entity === 'vendors') {
        title = 'Vendors';
        headers = ['Name', 'Phone', 'Email', 'Address', 'Status', 'Fleet Size', 'Created'];
        rows = vendors.map((v: any) => [
          v.name, v.phone, v.email || '', v.address || '', v.status, String(v.fleetSize), v.createdAt || '',
        ]);
      } else {
        title += ` + Vendors`;
        const vHeaders = ['Type', 'Name', 'Phone', 'Status', 'Fleet'];
        const vRows = vendors.map((v: any) => [
          'Vendor', v.name, v.phone, v.status, String(v.fleetSize),
        ]);
        rows = rows.map((row, i) => [...row, ...(vRows[i] || [])]);
        headers = [...headers, ...vHeaders.slice(1)];
      }
    }

    if (entity === 'all') {
      title = 'Full_System_Export';
    }

    if (format === 'csv') {
      await shareCsv(title, headers, rows);
    } else {
      await sharePdf(title, headers, rows);
    }
  } catch (e: any) {
    Alert.alert('Export Error', e?.message || 'Failed to export data');
  }
}