import { Platform, Alert, Share } from 'react-native';
import { Paths, File } from 'expo-file-system';
import * as ExpoSharing from 'expo-sharing';
import * as Print from 'expo-print';
import { fetchDrivers, fetchVehicles, fetchPurchaseOrders, fetchDeliveryOrders, fetchVendors } from '../services/api';

function escapeCsvField(value: any): string {
  if (value == null || value === undefined) return '';
  const str = String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function formatCsv(headers: string[], rows: string[][]): string {
  const hdr = headers.map(escapeCsvField).join(',');
  const body = rows.map(row => row.map(escapeCsvField).join(',')).join('\n');
  return `${hdr}\n${body}`;
}

export function buildHtmlTable(headers: string[], rows: string[][], title: string): string {
  const headerCells = headers.map(h => `<th style="padding:10px 14px; background:#1B2A4A; color:#fff; font-weight:700; text-align:left; border:1px solid #ddd;">${h}</th>`).join('');
  const bodyRows = rows.map((row, i) => {
    const bg = i % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
    const cells = row.map(cell => `<td style="padding:8px 14px; border:1px solid #ddd;">${cell || '—'}</td>`).join('');
    return `<tr style="background:${bg};">${cells}</tr>`;
  }).join('');

  return `
    <html>
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
    <body style="font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1E293B;">
      <h1 style="color: #1B2A4A; margin-bottom: 4px;">Trucks Sphere</h1>
      <h2 style="color: #475569; font-size: 18px; margin-top: 0; margin-bottom: 24px;">${title}</h2>
      <p style="color: #94A3B8; font-size: 12px;">Exported on ${new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })}</p>
      <table style="width:100%; border-collapse:collapse; font-size:13px; margin-top:12px;">
        <thead><tr>${headerCells}</tr></thead>
        <tbody>${bodyRows}</tbody>
      </table>
      <p style="color: #94A3B8; font-size: 10px; margin-top: 32px; text-align:center;">Generated by Trucks Sphere</p>
    </body>
    </html>
  `;
}

/**
 * Writes CSV content to a temp file and shares it as an actual .csv file.
 * Uses the new expo-file-system v56 API (Paths.cache + File).
 * Falls back to Share.share (plain text) on web or if file sharing fails.
 */
async function shareCsvFile(title: string, headers: string[], rows: string[][]) {
  const csv = formatCsv(headers, rows);
  const safeName = title.replace(/[^a-zA-Z0-9_-]/g, '_');
  const fileName = `${safeName}.csv`;

  try {
    if (Platform.OS === 'web') {
      // Web: use Blob download
      const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      return;
    }

    // Native: write CSV to cache directory using new File API
    const csvFile = new File(Paths.cache, fileName);
    csvFile.write('\uFEFF' + csv);

    const canShare = await ExpoSharing.isAvailableAsync();
    if (canShare) {
      await ExpoSharing.shareAsync(csvFile.uri, {
        mimeType: 'text/csv',
        dialogTitle: title,
        UTI: 'public.comma-separated-values-text',
      });
    } else {
      await Share.share({ message: csv, title });
    }
  } catch (e: any) {
    if (e?.message !== 'User did not share' && e?.message !== 'CANCELED') {
      try {
        await Share.share({ message: csv, title });
      } catch (_: any) {
        if (_?.message !== 'User did not share') {
          Alert.alert('Export Error', _?.message || 'Failed to share CSV');
        }
      }
    }
  }
}

/**
 * Generates a PDF file from HTML and shares it as an actual .pdf file.
 * Uses expo-print to generate the PDF, then expo-sharing to share it.
 * Falls back to Share.share (HTML text) on web or if PDF sharing fails.
 */
async function sharePdfFile(title: string, headers: string[], rows: string[][]) {
  const html = buildHtmlTable(headers, rows, title);
  const safeName = title.replace(/[^a-zA-Z0-9_-]/g, '_');
  const fileName = `${safeName}.pdf`;

  try {
    if (Platform.OS === 'web') {
      await Print.printAsync({ html, width: 595, height: 842 });
      return;
    }

    // Generate PDF via expo-print
    const { uri } = await Print.printToFileAsync({ html, width: 595, height: 842, base64: false });

    // Copy to cache with a friendly name using new File API
    const pdfFile = new File(Paths.cache, fileName);
    const tempFile = new File(uri);
    await tempFile.copy(pdfFile);

    const canShare = await ExpoSharing.isAvailableAsync();
    if (canShare) {
      await ExpoSharing.shareAsync(pdfFile.uri, {
        mimeType: 'application/pdf',
        dialogTitle: title,
        UTI: 'com.adobe.pdf',
      });
    } else {
      await Share.share({ message: html, title });
    }
  } catch (e: any) {
    if (e?.message !== 'User did not share' && e?.message !== 'CANCELED') {
      try {
        await Share.share({ message: html, title });
      } catch (_: any) {
        if (_?.message !== 'User did not share') {
          Alert.alert('Export Error', _?.message || 'Failed to share PDF');
        }
      }
    }
  }
}

// ============== DELIVERY NOTE EXPORT ==============

export interface DeliveryNoteExportData {
  jobId: string;
  poNumber: string;
  vendorName: string;
  driverName: string;
  plateNumber: string;
  materialName: string;
  quantityOrdered: number;
  quarryName: string;
  siteName: string;
  netWeight: string;
  status: string;
  createdAt: string;
  weighInWeight?: string;
  weighOutWeight?: string;
}

export async function shareDeliveryNoteCSV(data: DeliveryNoteExportData) {
  const headers = ['Field', 'Value'];
  const rows = [
    ['Delivery Note #', data.jobId],
    ['Purchase Order', data.poNumber],
    ['Vendor', data.vendorName],
    ['Driver', data.driverName],
    ['Truck', data.plateNumber],
    ['Material', data.materialName],
    ['Ordered Qty', `${data.quantityOrdered} tonnes`],
    ['Origin', data.quarryName],
    ['Destination', data.siteName],
    ['Weigh-In', data.weighInWeight ? `${data.weighInWeight} t` : '—'],
    ['Weigh-Out', data.weighOutWeight ? `${data.weighOutWeight} t` : '—'],
    ['Net Weight', `${data.netWeight} tonnes`],
    ['Status', data.status.replace(/_/g, ' ').toUpperCase()],
    ['Date Created', data.createdAt],
  ];
  await shareCsvFile(`Delivery_Note_${data.jobId}`, headers, rows);
}

export async function shareDeliveryNotePDF(data: DeliveryNoteExportData) {
  const headers = ['Field', 'Value'];
  const rows = [
    ['Delivery Note #', data.jobId],
    ['Purchase Order', data.poNumber],
    ['Vendor', data.vendorName],
    ['Driver', data.driverName],
    ['Truck', data.plateNumber],
    ['Material', data.materialName],
    ['Ordered Qty', `${data.quantityOrdered} tonnes`],
    ['Origin', data.quarryName],
    ['Destination', data.siteName],
    ['Weigh-In', data.weighInWeight ? `${data.weighInWeight} t` : '—'],
    ['Weigh-Out', data.weighOutWeight ? `${data.weighOutWeight} t` : '—'],
    ['Net Weight', `${data.netWeight} tonnes`],
    ['Status', data.status.replace(/_/g, ' ').toUpperCase()],
    ['Date Created', data.createdAt],
  ];
  await sharePdfFile(`Delivery Note - ${data.jobId}`, headers, rows);
}

// ============== SYSTEM-WIDE EXPORTS ==============

export type ExportEntity = 'drivers' | 'trucks' | 'purchase_orders' | 'deliveries' | 'vendors' | 'all';

export async function exportDataAsCSV(entity: ExportEntity) {
  await doExport(entity, 'csv');
}

export async function exportDataAsPDF(entity: ExportEntity) {
  await doExport(entity, 'pdf');
}

/**
 * Fetches and builds exportable data as structured headers + rows for UI column selection.
 */
export async function fetchExportData(entity: ExportEntity): Promise<{
  title: string;
  headers: string[];
  rows: string[][];
}> {
  try {
    let title = '';
    let headers: string[] = [];
    let rows: string[][] = [];

    if (entity === 'drivers') {
      const drivers = await fetchDrivers();
      title = 'Drivers';
      headers = ['Name', 'Phone', 'Email', 'License', 'License Expiry', 'Status', 'Vendor ID', 'Assigned Truck', 'Created'];
      rows = drivers.map((d: any) => [
        d.name, d.phone, d.email || '', d.licenseNumber, d.licenseExpiry || '',
        d.status, d.vendorId || '', d.assignedTruckId || '', d.createdAt || '',
      ]);
    } else if (entity === 'trucks') {
      const vehicles = await fetchVehicles();
      title = 'Trucks';
      headers = ['Plate', 'Model', 'Make', 'Year', 'Color', 'Capacity (t)', 'Status', 'Vendor', 'Driver', 'Insurance', 'Last Inspection'];
      rows = vehicles.map((v: any) => [
        v.plateNumber, v.model, v.make, String(v.year), v.color, String(v.capacity),
        v.status, v.vendorName || '', v.driverName || '', v.insuranceExpiry || '', v.lastInspection || '',
      ]);
    } else if (entity === 'purchase_orders') {
      const orders = await fetchPurchaseOrders();
      title = 'Purchase Orders';
      headers = ['PO Number', 'Vendor', 'Material', 'Quantity', 'Unit', 'Unit Price', 'Total', 'Status', 'Quarry', 'Site', 'Created'];
      rows = orders.map((o: any) => [
        o.poNumber, o.vendorName, o.materialName, String(o.quantity), o.unit,
        String(o.unitPrice), String(o.totalAmount), o.status, o.quarryName, o.siteName, o.createdAt,
      ]);
    } else if (entity === 'deliveries') {
      const deliveries = await fetchDeliveryOrders();
      title = 'Deliveries';
      headers = ['Job ID', 'PO Number', 'Vendor', 'Driver', 'Truck', 'Material', 'Ordered Qty', 'Net Weight', 'Status', 'Quarry', 'Site', 'Created'];
      rows = deliveries.map((d: any) => [
        d.jobId, d.poNumber, d.vendorName, d.driverName, d.plateNumber, d.materialName,
        `${d.quantityOrdered} ${d.unit || 'tonnes'}`, d.netWeight ? `${d.netWeight} t` : '—',
        d.status, d.quarryName, d.siteName, d.createdAt,
      ]);
    } else if (entity === 'vendors') {
      const vendors = await fetchVendors();
      title = 'Vendors';
      headers = ['Name', 'Phone', 'Email', 'Address', 'Status', 'Fleet Size', 'Created'];
      rows = vendors.map((v: any) => [
        v.name, v.phone, v.email || '', v.address || '', v.status, String(v.fleetSize), v.createdAt || '',
      ]);
    } else if (entity === 'all') {
      // Build interlinked export similar to doExport
      const [drivers, vehicles, orders, deliveries, vendors] = await Promise.all([
        fetchDrivers(), fetchVehicles(), fetchPurchaseOrders(), fetchDeliveryOrders(), fetchVendors(),
      ]);
      title = 'Full_System_Export';
      headers = ['Type', 'Name', 'Phone', 'Email', 'License', 'Status', 'Created'];
      const dRows = drivers.map((d: any) => [
        'Driver', d.name, d.phone, d.email || '', d.licenseNumber, d.status, d.createdAt || '',
      ]);
      const vhHeaders = ['Plate', 'Model', 'Make', 'Status', 'Capacity (t)'];
      const vhRows = vehicles.map((v: any) => [
        'Truck', v.plateNumber, v.model, v.make, v.status, String(v.capacity),
      ]);
      const poH = ['PO Number', 'Vendor', 'Material', 'Qty', 'Status', 'Total (KES)'];
      const poRows = orders.map((o: any) => [
        'Order', o.poNumber, o.vendorName, o.materialName, `${o.quantity} ${o.unit}`, o.status, `KES ${o.totalAmount?.toLocaleString()}`,
      ]);
      const delH = ['Job ID', 'Driver', 'Truck', 'Material', 'Status'];
      const delRows = deliveries.map((d: any) => [
        'Delivery', d.jobId, d.driverName, d.plateNumber, d.materialName, d.status,
      ]);
      const vH = ['Name', 'Phone', 'Status', 'Fleet'];
      const vRows = vendors.map((v: any) => [
        'Vendor', v.name, v.phone, v.status, String(v.fleetSize),
      ]);
      rows = [...dRows, ...vhRows, ...poRows, ...delRows, ...vRows];
    }

    return { title, headers, rows };
  } catch (e: any) {
    Alert.alert('Export Error', e?.message || 'Failed to fetch export data');
    throw e;
  }
}

async function doExport(entity: ExportEntity, format: 'csv' | 'pdf') {
  try {
    let title = '';
    let headers: string[] = [];
    let rows: string[][] = [];

    if (entity === 'drivers' || entity === 'all') {
      const drivers = await fetchDrivers();
      title += title ? ' + Drivers' : 'Drivers';
      if (entity === 'drivers') {
        headers = ['Name', 'Phone', 'Email', 'License', 'License Expiry', 'Status', 'Vendor ID', 'Assigned Truck', 'Created'];
        rows = drivers.map((d: any) => [
          d.name, d.phone, d.email || '', d.licenseNumber, d.licenseExpiry || '',
          d.status, d.vendorId || '', d.assignedTruckId || '', d.createdAt || '',
        ]);
      } else {
        const dHeaders = ['Type', 'Name', 'Phone', 'Email', 'License', 'Status', 'Created'];
        const dRows = drivers.map((d: any) => [
          'Driver', d.name, d.phone, d.email || '', d.licenseNumber, d.status, d.createdAt || '',
        ]);
        headers = dHeaders;
        rows = dRows;
      }
    }

    if (entity === 'trucks' || entity === 'all') {
      const vehicles = await fetchVehicles();
      const prefix = title ? ' + ' : '';
      title += `${prefix}Trucks`;
      if (entity === 'trucks') {
        headers = ['Plate', 'Model', 'Make', 'Year', 'Color', 'Capacity (t)', 'Status', 'Vendor', 'Driver', 'Insurance', 'Last Inspection'];
        rows = vehicles.map((v: any) => [
          v.plateNumber, v.model, v.make, String(v.year), v.color, String(v.capacity),
          v.status, v.vendorName || '', v.driverName || '', v.insuranceExpiry || '', v.lastInspection || '',
        ]);
      } else {
        const vHeaders = headers.length === 0 ? ['Type', 'Plate', 'Model', 'Make', 'Status', 'Capacity (t)'] : headers;
        const vRows = vehicles.map((v: any) => [
          'Truck', v.plateNumber, v.model, v.make, v.status, String(v.capacity),
        ]);
        if (headers.length === 0) {
          headers = vHeaders;
          rows = vRows;
        } else {
          rows = rows.map((row, i) => [...row, ...(vRows[i] || [])]);
          headers = [...headers, ...vHeaders.slice(1)];
        }
      }
    }

    if (entity === 'purchase_orders' || entity === 'all') {
      const orders = await fetchPurchaseOrders();
      if (entity === 'purchase_orders') {
        title = 'Purchase Orders';
        headers = ['PO Number', 'Vendor', 'Material', 'Quantity', 'Unit', 'Unit Price', 'Total', 'Status', 'Quarry', 'Site', 'Created'];
        rows = orders.map((o: any) => [
          o.poNumber, o.vendorName, o.materialName, String(o.quantity), o.unit,
          String(o.unitPrice), String(o.totalAmount), o.status, o.quarryName, o.siteName, o.createdAt,
        ]);
      } else {
        title += ` + Purchase Orders`;
        const poHeaders = ['Type', 'PO Number', 'Vendor', 'Material', 'Qty', 'Status', 'Total (KES)'];
        const poRows = orders.map((o: any) => [
          'Order', o.poNumber, o.vendorName, o.materialName, `${o.quantity} ${o.unit}`, o.status, `KES ${o.totalAmount?.toLocaleString()}`,
        ]);
        rows = rows.map((row, i) => [...row, ...(poRows[i] || [])]);
        headers = [...headers, ...poHeaders.slice(1)];
      }
    }

    if (entity === 'deliveries' || entity === 'all') {
      const deliveries = await fetchDeliveryOrders();
      if (entity === 'deliveries') {
        title = 'Deliveries';
        headers = ['Job ID', 'PO Number', 'Vendor', 'Driver', 'Truck', 'Material', 'Ordered Qty', 'Net Weight', 'Status', 'Quarry', 'Site', 'Created'];
        rows = deliveries.map((d: any) => [
          d.jobId, d.poNumber, d.vendorName, d.driverName, d.plateNumber, d.materialName,
          `${d.quantityOrdered} ${d.unit || 'tonnes'}`, d.netWeight ? `${d.netWeight} t` : '—',
          d.status, d.quarryName, d.siteName, d.createdAt,
        ]);
      } else {
        title += ` + Deliveries`;
        const dHeaders = ['Type', 'Job ID', 'Driver', 'Truck', 'Material', 'Status'];
        const dRows = deliveries.map((d: any) => [
          'Delivery', d.jobId, d.driverName, d.plateNumber, d.materialName, d.status,
        ]);
        rows = rows.map((row, i) => [...row, ...(dRows[i] || [])]);
        headers = [...headers, ...dHeaders.slice(1)];
      }
    }

    if (entity === 'vendors' || entity === 'all') {
      const vendors = await fetchVendors();
      if (entity === 'vendors') {
        title = 'Vendors';
        headers = ['Name', 'Phone', 'Email', 'Address', 'Status', 'Fleet Size', 'Created'];
        rows = vendors.map((v: any) => [
          v.name, v.phone, v.email || '', v.address || '', v.status, String(v.fleetSize), v.createdAt || '',
        ]);
      } else {
        title += ` + Vendors`;
        const vHeaders = ['Type', 'Name', 'Phone', 'Status', 'Fleet'];
        const vRows = vendors.map((v: any) => [
          'Vendor', v.name, v.phone, v.status, String(v.fleetSize),
        ]);
        rows = rows.map((row, i) => [...row, ...(vRows[i] || [])]);
        headers = [...headers, ...vHeaders.slice(1)];
      }
    }

    if (entity === 'all') {
      title = 'Full_System_Export';
    }

    if (format === 'csv') {
      await shareCsvFile(title, headers, rows);
    } else {
      await sharePdfFile(title, headers, rows);
    }
  } catch (e: any) {
    Alert.alert('Export Error', e?.message || 'Failed to export data');
  }
}

// ============== Exported helper functions (used by history screens inline) ==============

/**
 * Build CSV content string from headers and rows.
 */
export function buildCsvContent(headers: string[], rows: string[][]): string {
  return formatCsv(headers, rows);
}

/**
 * Build HTML table string for PDF generation from headers and rows.
 */
export function buildHtmlContent(headers: string[], rows: string[][], title: string): string {
  return buildHtmlTable(headers, rows, title);
}

/**
 * Share a CSV file using the new expo-file-system API (Paths.cache + File.write).
 * Writes to the cache directory and shares as an actual .csv file.
 * Falls back to plain text Share.share on failure.
 */
export async function shareCsvAsFile(title: string, csvContent: string): Promise<void> {
  const safeName = title.replace(/[^a-zA-Z0-9_-]/g, '_');
  const fileName = `${safeName}.csv`;

  try {
    if (Platform.OS === 'web') {
      const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      return;
    }

    const csvFile = new File(Paths.cache, fileName);
    csvFile.write('\uFEFF' + csvContent);

    const canShare = await ExpoSharing.isAvailableAsync();
    if (canShare) {
      await ExpoSharing.shareAsync(csvFile.uri, {
        mimeType: 'text/csv',
        dialogTitle: title,
        UTI: 'public.comma-separated-values-text',
      });
    } else {
      await Share.share({ message: csvContent, title });
    }
  } catch (e: any) {
    if (e?.message !== 'User did not share' && e?.message !== 'CANCELED') {
      try {
        await Share.share({ message: csvContent, title });
      } catch (_: any) {
        if (_?.message !== 'User did not share') {
          Alert.alert('Export Error', _?.message || 'Failed to share CSV');
        }
      }
    }
  }
}

/**
 * Share a PDF file using expo-print + expo-sharing + new expo-file-system API.
 * Generates PDF from HTML and shares as actual .pdf.
 * Falls back to plain text Share.share on failure.
 */
export async function sharePdfAsFile(title: string, htmlContent: string): Promise<void> {
  const safeName = title.replace(/[^a-zA-Z0-9_-]/g, '_');
  const fileName = `${safeName}.pdf`;

  try {
    if (Platform.OS === 'web') {
      await Print.printAsync({ html: htmlContent, width: 595, height: 842 });
      return;
    }

    const { uri } = await Print.printToFileAsync({ html: htmlContent, width: 595, height: 842, base64: false });

    // Copy generated PDF to cache with friendly name
    const pdfFile = new File(Paths.cache, fileName);
    const tempFile = new File(uri);
    await tempFile.copy(pdfFile);

    const canShare = await ExpoSharing.isAvailableAsync();
    if (canShare) {
      await ExpoSharing.shareAsync(pdfFile.uri, {
        mimeType: 'application/pdf',
        dialogTitle: title,
        UTI: 'com.adobe.pdf',
      });
    } else {
      await Share.share({ message: htmlContent, title });
    }
  } catch (e: any) {
    if (e?.message !== 'User did not share' && e?.message !== 'CANCELED') {
      try {
        await Share.share({ message: htmlContent, title });
      } catch (_: any) {
        if (_?.message !== 'User did not share') {
          Alert.alert('Export Error', _?.message || 'Failed to share PDF');
        }
      }
    }
  }
}

// Legacy re-export (used by operator-quarry/history.tsx and operator-site/history.tsx)
export { shareCsvFile, sharePdfFile };